# Generated by Django 5.1.1 on 2024-09-17 06:37

import emailapp.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[emailapp.utils.validate_custom_email])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
